#!/bin/bash
# GitHub Token 推送脚本

echo "📋 GitHub Token 推送设置指南"
echo "=================================="
echo ""
echo "步骤 1: 创建 GitHub Token"
echo "---------------------------"
echo "1. 访问: https://github.com/settings/tokens"
echo "2. 点击 'Generate new token' -> 'Generate new token (classic)'"
echo "3. 勾选权限:"
echo "   ✅ repo (完整仓库访问权限)"
echo "   ✅ workflow (GitHub Actions 权限)"
echo "4. 设置过期时间"
echo "5. 点击 'Generate token'"
echo "6. 📝 复制 Token（只显示一次，保存好！）"
echo ""
echo "步骤 2: 推送代码"
echo "---------------------------"
echo "运行以下命令（替换 TOKEN 和 USERNAME）："
echo ""
echo "cd /Users/yantaomac/.openclaw/workspace/projects/follow-builders-notion"
echo ""
echo "# 如果还没有初始化 git"
echo "git init"
echo ""
echo "# 添加远程仓库"
echo "git remote add origin https://YOUR_TOKEN@github.com/YOUR_USERNAME/follow-builders-notion.git"
echo ""
echo "# 添加所有文件"
echo "git add ."
echo ""
echo "# 提交"
echo "git commit -m 'Initial commit: Follow Builders Daily Digest automation'"
echo ""
echo "# 推送"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "步骤 3: 设置 GitHub Secret"
echo "---------------------------"
echo "1. 进入仓库 Settings -> Secrets and variables -> Actions"
echo "2. 点击 New repository secret"
echo "3. Name: NOTION_API_KEY"
echo "4. Value: $(cat ~/.config/notion/api_key)"
echo "5. 点击 Add secret"
echo ""
